spring:
  h2:
    console:
      enabled: true

  datasource:
    url : jdbc:mysql://rtbox.synology.me:3307/gogs?zeroDateTimeBehavior=convertToNull&useSSL=false&verifyServerCertificate=false&useUnicode=true&characterEncoding=utf8&autoReconnection=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: returnBox!1016

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  redis:
    port: 6379
    host: 172.17.0.2

  thymeleaf:
    cache: false
    check-template-location: true

  mvc:
    static-path-pattern: /static/**


logging:
  level:
    co.test: DEBUG

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

